services:
  - type: web
    name: pokemon-discord-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: INFO
      - key: HEALTH_CHECK_PORT
        value: "10000"
      - key: MONITORING_INTERVAL
        value: "60"
      - key: MAX_CONCURRENT
        value: "10"
      - key: BACKUP_ENABLED
        value: "true"
      - key: METRICS_ENABLED
        value: "true"
    disk:
      name: pokemon-bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1