
# Ultra-Fast Monitoring Configuration
monitoring:
  ultra_fast_mode: true
  base_interval: 0.5          # 500ms base interval
  jitter_range: [0.1, 0.3]    # Minimal jitter for speed
  max_concurrent: 20          # High concurrency
  connection_pool_size: 50    # Large connection pool
  
  # Speed optimizations
  skip_unnecessary_checks: true
  cache_aggressive: true
  batch_process: true
  parallel_execution: true
  
  # Anti-detection (minimal impact on speed)
  stealth_mode: "balanced"    # Balance between speed and stealth
  user_agent_rotation: 5      # Quick rotation
  
performance:
  target_response_time: 0.3   # 300ms target
  max_memory_usage: 100       # 100MB limit
  cpu_optimization: true
  network_optimization: true
